rubocop/rubocop-factory_bot

README.md, docs/antora.yml, docs/modules/ROOT/pages/index.adoc, docs/modules/ROOT/pages/usage.adoc, rubocop-factory_bot.gemspec
This PR use factory_bot instead of FactoryBot.
=> Use factory_bot instead of FactoryBot

docs/modules/ROOT/pages/cops_factorybot.adoc, lib/rubocop/cop/factory_bot/consistent_parentheses_style.rb
This PR enhance documentation for `FactoryBot/ConsistentParenthesesStyle`.
=> Enhance documentation for `FactoryBot/ConsistentParenthesesStyle`

lib/rubocop/cop/factory_bot/attribute_defined_statically.rb, lib/rubocop/cop/factory_bot/consistent_parentheses_style.rb, lib/rubocop/cop/factory_bot/create_list.rb
This PR is correct indentation.
=> Correct indentation

lib/rubocop/cop/factory_bot/create_list.rb
This PR is remove unnecessary `$` captures.
=> Remove unnecessary `$` captures

config/default.yml, docs/modules/ROOT/pages/cops_factorybot.adoc, docs/modules/ROOT/pages/development.adoc, lib/rubocop/cop/factory_bot/consistent_parentheses_style.rb, lib/rubocop/factory_bot/factory_bot.rb, lib/rubocop/factory_bot/language.rb, lib/rubocop/factory_bot/version.rb, spec/rubocop/cop/factory_bot/attribute_defined_statically_spec.rb, spec/rubocop/cop/factory_bot/consistent_parentheses_style_spec.rb
=> Use factory_bot everywhere

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_factorybot.adoc, lib/rubocop/cop/factory_bot/create_list.rb
See also the disscussion about its safety at:
- https://github.com/rubocop/rubocop-rspec/pull/1467#discussion_r1015036219
If you have created a new cop:
=> Mark `FactoryBot/CreateList` as `SafeAutoCorrect: false`

README.md, docs/modules/ROOT/pages/index.adoc
This PR is add a link to factory_bot in the documentation.
=> Add a link to factory_bot in the documentation

CHANGELOG.md
This PR is remove duplicate CHANGELOG.
=> Remove duplicate CHANGELOG

CHANGELOG.md, config/default.yml, docs/antora.yml, docs/modules/ROOT/pages/cops_factorybot.adoc, lib/rubocop/factory_bot/version.rb
=> Release v2.23.0

CHANGELOG.md, lib/rubocop/cop/factory_bot/association_style.rb, spec/rubocop/cop/factory_bot/association_style_spec.rb
=> Fix AssociationStyle for blockless factory definitions

spec/rubocop/cop/factory_bot/factory_association_with_strategy_spec.rb
=> Add an explanation to #39

docs/modules/ROOT/pages/cops_factorybot.adoc, lib/rubocop/cop/factory_bot/association_style.rb
Clarifies how to fix this offense
If you have created a new cop:
=> Add an example for an association with factory

CHANGELOG.md, lib/rubocop/cop/factory_bot/association_style.rb, spec/rubocop/cop/factory_bot/association_style_spec.rb
=> Fix AssociationStyle to ignore strategy: :build

lib/rubocop/cop/factory_bot/create_list.rb
This PR remove unnecessary `$`
=> Remove unnecessary `$`

.rubocop.yml
Follow up: https://github.com/rubocop/rubocop-rspec/pull/1680
=> Use offense instead of violation

config/default.yml, docs/modules/ROOT/pages/cops_factorybot.adoc
Fix: https://github.com/rubocop/rubocop-factory_bot/issues/72
=> Fix some wrong release version in v2.24

CHANGELOG.md, spec/project/changelog_spec.rb
Follow up: https://github.com/rubocop/rubocop-rspec/pull/1721
=> Improve for project_spec

spec/rubocop/cop/factory_bot/consistent_parentheses_style_spec.rb
=> Add expect_correction for `FactoryBot/ConsistentParenthesesStyle` when call with an explicit receiver

.github/workflows/danger.yml, .github/workflows/main.yml
=> Use Ruby 3.3 in GHA jobs

CHANGELOG.md, config/default.yml, docs/antora.yml, docs/modules/ROOT/pages/cops_factorybot.adoc, lib/rubocop/factory_bot/version.rb
=> Bump version v2.25.0

lib/rubocop/cop/factory_bot/create_list.rb
Follow up: https://github.com/rubocop/rubocop-rspec/pull/1761
=> Use squiggly heredocs wherever possible

CHANGELOG.md, lib/rubocop/factory_bot/version.rb
=> Bump version v2.25.1

docs/modules/ROOT/pages/cops_factorybot.adoc
=> Generate cops documentation

.rubocop.yml, Gemfile
=> Bump rubocop-rspec to 2.29.2 and enable new cops

Rakefile, lib/rubocop/factory_bot/cop/generator.rb
before:
```
Do 4 steps:
1. Modify the description of FactoryBot/CopName in config/default.yml
2. Implement your new cop in the generated file!
3. Commit your new cop with a message such as
e.g. "Add new `FactoryBot/CopName` cop"
4. Run `bundle exec rake changelog:new` to generate a changelog entry
```
after:
```
Do 4 steps:
1. Modify the description of FactoryBot/CopName in config/default.yml
2. Implement your new cop in the generated file!
3. Commit your new cop with a message such as
e.g. "Add new `FactoryBot/CopName` cop"
4. Add an entry about new cop to CHANGELOG.md
```
- [-] Added an entry to the …
=> Change step with new_cop command for rubocop-factory_bot

docs/modules/ROOT/pages/development.adoc
=> Better cop rename examples

.github/workflows/publish.yml
____________________________________________________________________
=> Fix a publish workflow

CHANGELOG.md, config/default.yml, docs/antora.yml, docs/modules/ROOT/pages/cops_factorybot.adoc, lib/rubocop/factory_bot/version.rb
=> Release v2.26.0

.rubocop.yml, Gemfile
=> Remove unnecessary RuboCop RSpec settings

docs/modules/ROOT/pages/cops_factorybot.adoc
Similar to https://github.com/rubocop/rubocop-rspec/pull/1979
=> Add missing anchors

.github/workflows/danger.yml, .github/workflows/main.yml
Ruby 3.4 has been released🎉
https://www.ruby-lang.org/en/news/2024/12/25/ruby-3-4-0-released/
If you have created a new cop:
=> Update Ruby version in GitHub Actions workflow to 3.4

CHANGELOG.md, lib/rubocop/factory_bot/version.rb
=> Release v2.27.1
