- CHANGELOG.md
- docs/antora.yml
- lib/rubocop/factory_bot/version.rb
> Release 2.22.0

- .github/PULL_REQUEST_TEMPLATE.md
When I was writing a description to create #19, I realized that this field was unnecessary. It makes sense in rubocop-rspec, but it doesn't in this repo.
> Remove unnecessary checklist item from pull request template

- spec/rubocop/cop/factory_bot/factory_name_style_spec.rb
- spec/rubocop/cop/factory_bot/syntax_methods_spec.rb
Just refactoring.
Test cases in the spec/rubocop/cop/ directory are automatically assigned the `:config` metadata, so there is no need to add this in individual test files.
https://github.com/rubocop/rubocop-factory_bot/blob/9801c7d91e14df508b61fab9c3d2da642a4ce564/spec/spec_helper.rb#L20-L28
When a new cop is added to this project in the future, a new test file will be created by referring to the existing test files (while copy-and-pasting some of them), so I thought it would be better to delete these redundant code. In fact, I noticed this when I tried to create a new test file with reference to the existing test files at #19.
> Remove unnecessary `:config` metadata from specs

- docs/modules/ROOT/pages/index.adoc
This PR is change to use common ASCII characters.
> Use U+002d instead of U+2013

- lib/rubocop/cop/factory_bot/attribute_defined_statically.rb
- lib/rubocop/cop/factory_bot/consistent_parentheses_style.rb
- lib/rubocop/cop/factory_bot/create_list.rb
- lib/rubocop/cop/factory_bot/factory_name_style.rb
- rubocop-factory_bot.gemspec
- spec/rubocop/cop/factory_bot/attribute_defined_statically_spec.rb
- spec/rubocop/factory_bot/config_formatter_spec.rb
- spec/rubocop/factory_bot/description_extractor_spec.rb
Just refactoring.
I found that some heredoc indentations are wrong, so I replaced all `<<-` with `<<~`. This way, `Layout/HeredocIndentation` will point out and autocorrect the mis-indentations. And also, since it does not include unnecessary whitespace, there is no longer need to add workaround on spec/rubocop/factory_bot/config_formatter_spec.rb.
Maybe the original code existed for Ruby 2.2- compatibility (`<<~` was introduced from Ruby 2.3), so we couldn't use this back then, but now it requires Ruby 2.7 or higher, so we can do this.
> Replace heredoc `<<-` with `<<~` and adjust indentation

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_factorybot.adoc
- lib/rubocop-factory_bot.rb
- lib/rubocop/cop/factory_bot/consistent_parentheses_style.rb
- lib/rubocop/cop/factory_bot/create_list.rb
- lib/rubocop/cop/factory_bot/factory_name_style.rb
- lib/rubocop/cop/factory_bot/mixin/configurable_explicit_only.rb
- spec/rubocop/cop/factory_bot/consistent_parentheses_style_spec.rb
- spec/rubocop/cop/factory_bot/create_list_spec.rb
- spec/rubocop/cop/factory_bot/factory_name_style_spec.rb
Follow up: https://github.com/rubocop/rubocop-rspec/pull/1482#issuecomment-1315496663
Resolve: https://github.com/rubocop/rubocop-factory_bot/issues/5
> Add `ExplicitOnly` configuration option to `FactoryBot/ConsistentParenthesesStyle`, `FactoryBot/CreateList` and `FactoryBot/FactoryNameStyle`

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops.adoc
- docs/modules/ROOT/pages/cops_factorybot.adoc
- lib/rubocop/cop/factory_bot/factory_association_with_strategy.rb
- lib/rubocop/cop/factory_bot_cops.rb
- spec/rubocop/cop/factory_bot/factory_association_with_strategy_spec.rb
Fixes #6
This cop will add an offense when a strategy is hardcoded to create an association in a factory.
factory :foo do
profile { create(:profile) }
end
factory :foo do
profile
end
factory :foo do
association :profile
end
factory :foo do
profile { association :profile }
end
If you have created a new cop:
> Add cop flag explicit factory bot dsl method usage in association

- CHANGELOG.md
- docs/modules/ROOT/pages/cops_factorybot.adoc
- lib/rubocop/cop/factory_bot/create_list.rb
- spec/rubocop/cop/factory_bot/create_list_spec.rb
Recreated from the following pull request:
- https://github.com/rubocop/rubocop-rspec/pull/1467
> Change `FactoryBot/CreateList` so that it checks same factory calls in an Array

- CHANGELOG.md
- lib/rubocop/cop/factory_bot/create_list.rb
- spec/rubocop/cop/factory_bot/create_list_spec.rb
~This PR is add support cases of offense for `FactoryBot/CreateList` when create call dees have method call in the argument, but it does not repeat multiple times.~
~In the case of multiple repeats, the following problems were ignored.~
~- https://github.com/rubocop/rubocop-rspec/issues/1087~
~However, if it is not repeated more than once, it is not a problem as an offense.~
This PR is change `FactoryBot/CreateList` so that it is not an offense if not repeated multiple times.
Fix: https://github.com/rubocop/rubocop-factory_bot/issues/49
> Change `FactoryBot/CreateList` so that it is not an offense if not repeated multiple times

- CHANGELOG.md
- lib/rubocop/cop/factory_bot/association_style.rb
- spec/rubocop/cop/factory_bot/association_style_spec.rb
Fix: https://github.com/rubocop/rubocop-factory_bot/issues/58
> Fix a false positive for `FactoryBot/AssociationStyle` when `association` is called in trait block and column name is keyword

- CHANGELOG.md
- lib/rubocop/cop/factory_bot/association_style.rb
- spec/rubocop/cop/factory_bot/association_style_spec.rb
Fix: https://github.com/rubocop/rubocop-factory_bot/issues/54
> Fix a false positive for `FactoryBot/AssociationStyle` when `EnforcedStyle: Explicit` and using trait within trait

- lib/rubocop/cop/factory_bot/association_style.rb
Fix: https://github.com/rubocop/rubocop-factory_bot/actions/runs/6063658775/job/16451253608?pr=67
```ruby
lib/rubocop/cop/factory_bot/association_style.rb:251:21: C: [Corrected] InternalAffairs/RedundantMethodDispatchNode: Remove the redundant send_node.
ancestor.send_node.method?(:factory) if ancestor.block_type?
^^^^^^^^^^
```
> Fix rubocop offense

- CHANGELOG.md
- docs/antora.yml
- lib/rubocop/factory_bot/version.rb
It has been more than 3 months since the last time and it is time to release the next version.
It would be good to include the next PR in the next release:
> Bump version to v2.24.0

- CHANGELOG.md
- lib/rubocop/cop/factory_bot/consistent_parentheses_style.rb
- spec/rubocop/cop/factory_bot/consistent_parentheses_style_spec.rb
Fix: https://github.com/rubocop/rubocop-factory_bot/issues/84
> Fix a false positive for `FactoryBot/ConsistentParenthesesStyle` when hash pinning

- rubocop-factory_bot.gemspec
Fix: https://github.com/rubocop/rubocop-factory_bot/issues/89
> Use `spec.add_runtime_dependency 'rubocop', '~> 1.41'`

- CHANGELOG.md
- lib/rubocop/cop/factory_bot/create_list.rb
- spec/rubocop/cop/factory_bot/create_list_spec.rb
Fix: https://github.com/rubocop/rubocop-factory_bot/issues/87
> Fix a false positive for `FactoryBot/CreateList`

- CHANGELOG.md
- lib/rubocop/cop/factory_bot/id_sequence.rb
- spec/rubocop/cop/factory_bot/id_sequence_spec.rb
Fix: https://github.com/rubocop/rubocop-factory_bot/issues/80
> Fix an error occurred for `FactoryBot/IdSequence` when `sequence` with non-symbol argument or without argument

- .rubocop.yml
- spec/spec_helper.rb
```
❯ bundle exec rubocop
Inspecting 42 files
.......................................C..
Offenses:
spec/spec_helper.rb:17:9: C: Performance/MethodObjectAsBlock: Use block explicitly instead of block-passing a method object.
.each(&method(:require))
^^^^^^^^^^^^^^^^^
42 files inspected, 1 offense detected
```
> Enable cop for pending rubocop-performance

- spec/rubocop/cop/factory_bot/redundant_factory_option_spec.rb
https://github.com/rubocop/rubocop-factory_bot/actions/runs/8295790896/job/22703558438
```
Running RuboCop...
RuboCop failed!
Inspecting 42 files
...................................C......
Offenses:
spec/rubocop/cop/factory_bot/redundant_factory_option_spec.rb:[5](https://github.com/rubocop/rubocop-factory_bot/actions/runs/8295790896/job/22703558438#step:5:6)0:[8](https://github.com/rubocop/rubocop-factory_bot/actions/runs/8295790896/job/22703558438#step:5:9): C: [Correctable] InternalAffairs/ExampleDescription: Description does not match use of expect_offense.
it 'registers no offense' do
^^^^^^^^^^^^^^^^^^^^^^
42 files inspected, 1 offense detected, 1 offense autocorrectable
```
Before submitting the PR make sure the …
> Fix `InternalAffairs/ExampleDescription`

- .github/workflows/main.yml
- spec/rubocop/cop/factory_bot/consistent_parentheses_style_spec.rb
- spec/spec_helper.rb
Follow up rubocop/rubocop-ast#277
> Add job for CI using Prism parser

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_factorybot.adoc
Follow up: https://github.com/rubocop/rubocop-rspec/pull/1899
> Support `AutoCorrect: contextual` option for LSP

- CHANGELOG.md
- lib/rubocop/factory_bot/version.rb
- rubocop-factory_bot.gemspec
follow up: https://github.com/rubocop/rubocop-rspec/pull/1901
> `AutoCorrect: contextual` needs rubocop v1.61

- tasks/cut_release.rake
This PR fixes rubocop offense
```
tasks/cut_release.rake:41:21: W: [Corrected] Lint/ImplicitStringConcatenation: Combine '\0' and "## #{version} (#{Time.now.strftime('%F')})\n\n" into a single string literal, rather than using implicit string concatenation. Or, if they were intended to be separate method arguments, separate them with a comma.
'\0' "## #{version} (#{Time.now.strftime('%F')})\n\n")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tasks/cut_release.rake:41:21: C: [Corrected] Style/StringConcatenation: Prefer string interpolation to string concatenation.
'\0' + "## #{version} (#{Time.now.strftime('%F')})\n\n")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Before submitting the PR make …
> Fix a rubocop offense

- CHANGELOG.md
- lib/rubocop/cop/factory_bot/consistent_parentheses_style.rb
- spec/rubocop/cop/factory_bot/consistent_parentheses_style_spec.rb
Fix #135 
When ConsistentParenthesesStyle is :omit_parentheses, we ignore factory calls that have an omitted hash value (ruby 3.1 shorthand syntax). Parentheses are required if the arguments end with the key of the omitted value. (e.g. `create(:user, name:)`)
However, if a trait was used, (e.g. `create(:user, :trait, name:)`) `omit_hash_value?` matcher did not match it, and thus it would be an offense and corrected to remove the parentheses - potentially causing a syntax error.
This change adds a wildcard to the `omit_hash_value?` matcher to allow any number of symbols at the start of the factory call (before the hash values).
- ~~[ ] Updated …
> Let ConsistentParenthesesStyle :omit_parentheses ignore trait + omitted hash value

- CHANGELOG.md
- lib/rubocop-factory_bot.rb
`require_relative 'rubocop/factory_bot/version'` was missing, causing the constant lookup for `Version::STRING` in `lib/rubocop/factory_bot/plugin.rb` to resolve to `RuboCop::Version::STRING` instead of `RuboCop::FactoryBot::Version::STRING`.
This PR fixes an issue where `rubocop -V` incorrectly displayed the RuboCop version instead of the rubocop-factory_bot version:
```console
$ bundle exec rubocop -V
1.73.2 (using Parser 3.3.7.1, rubocop-ast 1.38.1, analyzing as Ruby 2.7, running on ruby 3.4.2) [x86_64-darwin23]
- rubocop-performance 1.24.0
- rubocop-rake 0.7.1
- rubocop-capybara 1.73.2
- rubocop-factory_bot 1.73.2
- rubocop-rspec_rails 2.31.0
- rubocop-rspec 3.5.0
``` …
> Fix incorrect plugin version

- spec/rubocop/cop/factory_bot/consistent_parentheses_style_spec.rb
These probably pass for a while now already.
No more `broken_on: :prism` in the RuboCop org when this and https://github.com/rubocop/rubocop-ast/pull/372 are merged
> Remove prism skipped tests

- CHANGELOG.md
- lib/rubocop/cop/factory_bot/association_style.rb
- spec/rubocop/cop/factory_bot/association_style_spec.rb
```shell
1) RuboCop::Cop::FactoryBot::AssociationStyle when EnforcedStyle is :explicit when implicit association is called in trait block does not register an offense for `trait` without `factory` block
Failure/Error:
def autocorrect(corrector, node)
if style == :explicit
autocorrect_to_explicit_style(corrector, node)
else
autocorrect_to_implicit_style(corrector, node)
end
NoMethodError:
undefined method 'each_node' for nil
```
> Fix an error for `FactoryBot/AssociationStyle` cop

- CHANGELOG.md
- lib/rubocop/cop/factory_bot/consistent_parentheses_style.rb
- spec/rubocop/cop/factory_bot/consistent_parentheses_style_spec.rb
```
1) RuboCop::Cop::FactoryBot::ConsistentParenthesesStyle when EnforcedStyle is :omit_parentheses registers an offense with `kwsplat` node argument
Failure/Error: factory_call(node) { register_offense(node) }
NoMethodError:
undefined method 'value_omission?' for an instance of RuboCop::AST::KeywordSplatNode
```
> Fix an error for `FactoryBot/ConsistentParenthesesStyle` cop
